pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('index/', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('signup/',views.signup,name='signup'),
    path('logout/',views.logout,name='logout'),
    path('result/', views.result, name='result'),
    
    path('sirform/',views.sirform,name='sirform'),
    path('studentlogin/',views.studentlogin,name="studentlogin"),
    path('sign/',views.signing,name="signing"),



    
]

pollster/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/models.py
from django.db import models

# Create your models here.



class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    

    def __str__(self):
        return self.choice_text













class Sir(models.Model):
    name=models.CharField(max_length=100)
    rollno=models.IntegerField(max_length=10)
    def __str__(self):
        return self.name

class Student(models.Model):
    student=models.CharField(("enter your name"),max_length=50)
    father=models.CharField(("enter your father name"), max_length=50)   
    mother=models.CharField(("enter your father name"), max_length=50)   
    def __str__(self):
        return self.student
    
    

class Registration(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    id_name= models.CharField(max_length=100)
    gmail = models.EmailField()
    password = models.CharField(max_length=100)

    def __str__(self):
        return self.first_name


class Cricket(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    id_name= models.CharField(max_length=100)
    gmail = models.EmailField()
    password = models.CharField(max_length=100)
    
    def __str__(self):
        return self.id_name
    

polls/forms.py
from django import forms



class Sirform(forms.Form):
    name=forms.CharField()
    id_name=forms.IntegerField()
    
class Collegeform(forms.Form):
    st_name=forms.CharField(label="first name",max_length=100)
    ft_name=forms.CharField(max_length=100)
    mt_name=forms.CharField(max_length=100)
    
    

class RegistrationForm(forms.Form):
    first_name = forms.CharField(label='First Name', max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label='Last Name', max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    id_name = forms.CharField(label='ID', max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    gmail = forms.EmailField(label='Gmail', required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Create Password', max_length=100, required=True, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

polls/views.py
from django.template import loader
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import get_object_or_404, render,redirect
from django.urls import reverse
from django.contrib import messages

from .models import Question, Choice,Registration


# Get questions and display them

from django.contrib.auth.decorators import login_required
@login_required(login_url='polls:login')
def index(request):
    
    latest_question_list = Question.objects.order_by('-pub_date')
    
    context = {'latest_question_list': latest_question_list}
    
    
    return render(request, 'polls/index.html', context)

# Show specific question and choices




@login_required(login_url='polls:login')
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})

# Get question and display results
from django.shortcuts import render
from .models import Question


@login_required(login_url='polls:login')
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

@login_required(login_url='polls:login')
# Vote for a question choice
def result(request):
    all_questions = Question.objects.all()
    return render(request, 'polls/result.html', {'all_questions': all_questions})


@login_required(login_url='polls:login')
def vote(request, question_id):
    # print(request.POST['choice'])
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:index'))
    
    
    

from django.contrib.auth import authenticate, login as auth_login,logout as auth_logout
from django.shortcuts import render, redirect
from django.http import HttpResponse

def login(request):
    if request.method == "POST":
        username1 = request.POST["id"]
        password1 = request.POST["password"]
        user = authenticate(request, username=username1, password=password1)
        if user is not None:
            auth_login(request, user)
            return redirect('polls:index')
        else:
            return render(request, 'polls/login.html', {
                'error_message': "Enter valid credentials",
        })

    return render(request, 'polls/login.html')




from django.contrib.auth.models import User
def signup(request):
    if request.method=="POST":
        firstname=request.POST.get('first_name')
        lastname=request.POST.get('last_name')
        idname=request.POST.get('id_name')
        gmail=request.POST.get('gmail')
        password=request.POST.get('password')
        print(firstname,lastname,idname,gmail)
        my_user=User.objects.create_user(firstname,idname,password)
        my_user.save()
        return redirect('polls:login')
    # if request.method=='POST':
    #     form=RegistrationForm(request.POST)
    #     if form.is_valid():
    #         f_name=form.cleaned_data['first_name']
    #         l_name=form.cleaned_data['last_name']
    #         i_name=form.cleaned_data['id_name']
    #         mail=form.cleaned_data['gmail']
    #         p_word=form.cleaned_data['password']
    #         create_new=Registration(first_name=f_name,last_name=l_name,id_name=i_name,gmail=mail,password=p_word)
    #         create_new.save()
    #         return HttpResponseRedirect(reverse('polls:index'))
            
    form=RegistrationForm() 
    return render(request,"polls/signup.html",{'form':form}) 
    # return render(request,'polls/signup.html')

# def logout(request):
#     redirect(request)
#     return render(request,'pages/index.html')
from django.shortcuts import render, redirect
from django.contrib import admin




def logout(request):
    auth_logout(request)
    return render(request,'pages/index.html')



from django.shortcuts import redirect
from django.urls import reverse








from .forms import Sirform,Collegeform,RegistrationForm
from .models import Sir,Student,Registration

def sirform(request):
    if request.method=='POST':
        form=Sirform(request.POST)
        if form.is_valid():
            emp_name=form.cleaned_data['name']
            emp_id=form.cleaned_data['id_name']
            create_sir=Sir.objects.create(name=emp_name,rollno=emp_id)
            create_sir.save()
            return HttpResponse("data is saved")
            
    form=Sirform()
    return render(request,"polls/display_user_details.html",{'form':form})

def studentlogin(request):
    if request.method=='POST':
        new=Collegeform(request.POST)
        if new.is_valid():
            stu_name=new.cleaned_data['st_name']
            fat_name=new.cleaned_data['ft_name']
            mot_name=new.cleaned_data['mt_name']
            create_new=Student(student=stu_name,father=fat_name,mother=mot_name)
            create_new.save()
            return HttpResponse("data is saved successfully")
    new=Collegeform()
    return render(request,"polls/studentlogin.html",{'form':new})

def signing(request):
    if request.method=='POST':
        form=RegistrationForm(request.POST)
        if form.is_valid():
            f_name=form.cleaned_data['first_name']
            l_name=form.cleaned_data['last_name']
            i_name=form.cleaned_data['id_name']
            mail=form.cleaned_data['gmail']
            p_word=form.cleaned_data['password']
            create_new=Registration(first_name=f_name,last_name=l_name,id_name=i_name,gmail=mail,password=p_word)
            create_new.save()
            return HttpResponse("DATA IS SAVED SUCCESSFULLY")
            
    form=RegistrationForm() 
    return render(request,"polls/logout.html",{'form':form})      


# views.py

# from django.shortcuts import render, redirect
# from .models import ChoiceForm

# def add_choice(request, question_id):
#     if request.method == 'POST':
#         form = ChoiceForm(request.POST)
#         if form.is_valid():
#             new_choice = form.save(commit=False)
#             new_choice.question_id = question_id
#             new_choice.save()
#             return render(request,'poll/results.html')  # Redirect to a success page or any other desired page
#     else:
#         form = ChoiceForm()
    
#     return render(request, 'polls/login.html', {'form': form})


# polls/views.py

# from django.shortcuts import render
# from .forms import UserLoginForm

# def check(request):
#     if request.method == 'POST':
#         # Process the form data
#         form = UserLoginForm(request.POST)
#         if form.is_valid():
#             user_id = form.cleaned_data['user_id']
#             password = form.cleaned_data['password']
#             # Do something with the user_id and password, e.g., authentication
            
#             # Redirect to a success page or do other processing
#     else:
#         # Display a blank form
#         form = UserLoginForm()

#     return render(request, 'index.html', {'form': form})

templates/polls/detail.html
{% extends 'base.html' %}
{% block content %}
<br>
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'polls:index' %}">Back To Polls</a>

<a href="{% url 'polls:logout'%}" class="btn btn-secondary btn-sm float-right mb-2">Logout</a>

<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class="alert alert-danger">
    <strong>{{ error_message }}</strong>
</p>
{% endif %}
{% comment %} <h1>User Information</h1>
<p>User ID: {{ user_id }}</p>
<p>User Gmail: {{ user_gmail }}</p> {% endcomment %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <div class="form-check">
        <input type="radio" name="choice" class="form-check-input" id="choice{{ forloop.counter }}"
            value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    </div>
    {% endfor %}
    <input type="submit" value="Submit" class="btn btn-success btn-lg btn-block mt-4" />
</form>
{% endblock %}

templates/polls/display_user_details.html
{% extends 'base.html' %}
{% block content %}

<html>
    <h1>DETAILS</h1>
    <form action="" method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit">submit</button>
</html>

{% endblock %}

templates/polls/index.html
{% extends 'base.html' %}
{% block content %}

<h1 class="text-center mb-3">Welcome to {{user_id}}</h1>
<h1 class="text-center mb-3">Feedback Questions</h1>
<a href="{% url 'polls:logout'%}" class="btn btn-secondary btn-sm float-right mb-2">Logout</a>



{% if latest_question_list %}
  {% for question in latest_question_list %}
    <div class="card-mb-3">
      <div class="card-body">
        <p class="lead">{{ question.question_text }}</p>
        <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary btn-sm">Vote Now</a>
      </div>
    </div>
  {% endfor %}

  <!-- Display Results button after the loop -->
  <a href="{% url 'polls:result' %}" class="btn btn-secondary btn-sm float-right mb-2">Results</a>

{% else %}
  <p>No Questions available</p>
{% endif %}
{% comment %} <p>User Gmail: {{ user_gmail }}</p> {% endcomment %}
{% endblock %}





{% comment %} 

{% extends 'base.html' %}
{% block content %}
<h1 class="text-center mb-3">Feedback Questions</h1>
<a href="{% url 'polls:logout'%}" class="btn btn-secondary btn-sm float-right mb-2">Logout</a>
{% if latest_question_list %}
{% for question in latest_question_list %}
<div class="card-mb-3">
    <div class="card-body">
        <p class="lead">{{ question.question_text }}</p>
        <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary btn-sm">Vote Now</a>
        <a href="{% url 'polls:results' question.id %}" class="btn btn-secondary btn-sm">Results</a>
        
    </div>
</div>


{% comment %} <div class="card-mb-3">
    <div class="card-body">
        <p class="lead">{{ question.question_text }}</p>
        <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary btn-lg">Vote Now</a>
        <a href="{% url 'polls:results' question.id %}" class="btn btn-secondary btn-lg">Results</a>
    </div>
</div> {% endcomment %}

{% comment %} {% endfor %}

{% else %}
<p>No Questions available</p>
{% endif %}



{% endblock %} {% endcomment %} 
{% comment %} {% endcomment %}

templates/polls/login.html
{% extends 'base.html' %}
{% block content %}

{% if error_message %}
<p class="alert alert-danger">
    <strong>{{ error_message }}</strong>
</p>
{% endif %}

{% load static %}
{% block custom_css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock custom_css %}

<style>
    .custom-card-body {
        height: 0px;
    }
</style>

<div class="card text-center border-0">
    <div class="card-body custom-card-body">
        <h1>Welcome To Feedback System</h1>

        <form method="post" action="{% url 'polls:index' %}">
            {% csrf_token %}
            
            <!-- Input for ID -->
            <div class="form-group">
                <label for="idInput">ID:</label>
                <input type="text" class="form-control" id="idInput" name="id" required>
            </div>

            <!-- Input for Gmail -->
            <div class="form-group">
                <label for="passwordInput">Password:</label>
                <input type="password" class="form-control" id="passwordInput" name="password" required>
            </div>

            <!-- Submit Button -->
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

{% endblock %}

templates/polls/logout.html
{% extends 'base.html' %}
{% block content %}<h1>Details</h1>

<form method="post" action=" ">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>

{% endblock %}

templates/polls/result.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="mb-5 text-center">All Questions and Results</h1>

    {% for question in all_questions %}
        <h2 class="mb-3">{{ question.question_text }}</h2>

        <ul class="list-group mb-5">
            {% for choice in question.choice_set.all %}
                <li class="list-group-item">
                    {{ choice.choice_text }}
                    <span class="badge badge-success float-right">{{ choice.votes }} vote{{ choice.votes | pluralize }}</span>
                </li>
            {% endfor %}
        </ul>
    {% endfor %}

    <a href="{% url 'polls:logout' %}" class="btn btn-secondary btn-sm float-right mb-2">Logout</a>
{% endblock %}

templates/polls/results.html
{% extends 'base.html' %}
{% block content %}
<h1 class="mb-5 text-center">{{ question.question_text }}</h1>
 
<ul class="list-group mb-5">
    {% for choice in question.choice_set.all %}
    <li class="list-group-item">
        {{ choice.choice_text }} <span class="badge badge-success float-right">{{ choice.votes }}
            vote{{ choice.votes | pluralize }}</span>
    </li>
    {% endfor %}
</ul> 


<a class="btn btn-secondary" href="{% url 'polls:index' %}">Back To Polls</a>
<a href="{% url 'polls:logout'%}" class="btn btn-secondary btn-sm float-right mb-2">Logout</a>
{% comment %} <a class="btn btn-dark" href="{% url 'polls:detail' question.id %}">Vote again?</a> {% endcomment %}
{% endblock %}

templates/polls/signup.html
{% extends 'base.html' %}
{% block content %}

{% load static %}
{% block custom_css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock custom_css %}  

<style>
    .custom-card-body {
        height: 0px;
        
    }
</style>

<div class="card text-center border-0">
    <div class="card-body custom-card-body">
        <h1>Welcome To Feedback System</h1>

        <form method="post" action=" ">
            
            {% csrf_token %}
            {{ form.as_p }}

            <!-- Submit Button -->
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

{% endblock %}

templates/polls/studentlogin.html
<html>
    <h1>DETAILS</h1>
    <form action="" method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit">submit</button>
</html>