pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('index/', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('signup/',views.signup,name='signup'),
    path('logout/',views.logout,name='logout'),
    path('result/', views.result, name='result'),
    
    path('sirform/',views.sirform,name='sirform'),
    path('studentlogin/',views.studentlogin,name="studentlogin"),
    path('sign/',views.signing,name="signing"),



    
]

pollster/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

templates/pages/index.html
{% extends 'base.html' %}
{% block content %}

{% load static %}
{% block custom_css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock custom_css %}




<style>
    .custom-card-body {
        height: 0px;
    }
</style>

<div class="card text-center border-0">
    <div class="card-body custom-card-body">
        <h1><marquee scrolltime="10">Welcome To Feedback System</marquee></h1>
        <style>
            p {
                font-size: 20px;
                margin-bottom: 25px;
            }
        
        </style>
        
        
        {% comment %} <p>A feedback system is a crucial 
            component of any organization's 
            strategy to collect, analyze, 
            and respond to user opinions and experiences. 
        </p>
        <p>
            It serves as a mechanism for users to express their thoughts, 
            provide suggestions, and report issues related to products, 
            services, or interactions</p>
         {% endcomment %}
       <br>
        <a class="btn btn-dark btn-lg mr-5" href="{% url 'polls:login' %}">Login</a>
        <a class="btn btn-dark btn-lg" href="{% url 'polls:signup' %}">Signup</a>
    </div>
</div>

{% endblock %}